staticSites:
  - name: memory-card-game
    branch: main
    buildCommand: ""
    staticPublishPath: .

services:
  - type: web
    name: memory-card-game-web
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
